name: CI Checks
on:
  push:
  pull_request:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20
            registry-url: 'https://npm.pkg.github.com'
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Install dependencies
        run: npm ci
        
      - name: Run lint
        run: npm run lint
      
      - name: Run test
        run: npm run test
  
  check-dist:
    name: Check Distribution
    runs-on: ubuntu-latest
    
    env:
      BUNDLE_FILE: "dist/index.js"
      BUNDLE_COMMAND: "npm run bundle"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
            node-version: 20
            registry-url: 'https://npm.pkg.github.com'
        env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: npm ci

      - name: Verify Latest Bundle
        uses: redhat-actions/common/bundle-verifier@v1
        with:
          bundle_file: ${{ env.BUNDLE_FILE }}
          bundle_command: ${{ env.BUNDLE_COMMAND }}