# Template workflow for OpenShift GitHub Connector

name: Scan with Red Hat Dependency Analytics

on:
  push:
    branches: [ "n/a" ]
  pull_request_target:
    # https://github.com/redhat-actions/crda/#scanning-pull-requests
    types: [ "n/a" ]

jobs:
  crda-scan:
    name: Scan with Red Hat Dependency Analytics
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up environment
      # May use setup-[go|java|node|python]
      uses: actions/setup-node@v4
      with:
          node-version: '20'

    # https://github.com/redhat-actions/crda/
    - name: RHDA Scan
      id: rhda_scan
      uses: RHEcosystemAppEng/rhda-github-action@main